### ISSUE TITLE
Variations and Errors

### ISSUE THREAD

**Issue by j0sh** [livepeer/verification-classifier#1]
Some suggestions for things to look at while we're evaluating the classifier. In no particular order:

## Reasonable Variations

We might want to be tolerant to the following variations that could occur as a result of differences in transcoder implementation. However, we may still need to determine our tolerances for these variations; anything excessive should be flagged as an error.

* Timestamp alignment
* Frame selection
  * May be rounding differences with eg, variable frame rate input
  * One fps implementation may select even frames, another odd
  * Off-by-one differences?
* Pixel layout conversion between source / result may have rounding / interpolation issues
  * Bit depth (eg, 8bit <-> 10bit)
  * Colorspace (eg, RGB <-> YUV)
  * Chroma subsampling (eg, 4:4:4 -> 4:2:0)
* Rescaling
  * Especially in upscaling

## Errors

Some possible attacks or unreasonable flaws in the video may include:

* Bitrate
  * eg, 720p output should not have a higher bitrate than an 1080p source
  * Is there a consistent relationship between resolution and bitrate given reasonable encoding settings? Need to account for well-optimized sources.
* Rotations
* Watermarking, vignetting
* Color shifting, excessive color correction, filters
* Low quality encodes

**Comment by Sorkanius** [comment]
We will create a pre-verification methods that checks this information before performing feature calculation and inference

**Comment by ndujar** [comment]
A dataset of videos containing the above variations has been created.
There are specific scripts to generate such dataset as described [here](https://github.com/livepeer/verification-classifier/blob/master/scripts/README.md) from any collection of videos.
Using YT8M dataset, we have made available trimmed segments of 10s [here](https://storage.googleapis.com/livepeer-verifier-originals), and their respective modified renditions [here](https://storage.googleapis.com/livepeer-verifier-renditions).
Interested users of the data set (beware it amounts to about 4k originals and 200k variation samples, totaling a very large disk space), can do so by inputting the following lines in their terminal:
* For original 1080p segments, 10s duration:
```
gsutil -m cp -r gs://livepeer-verifier-originals .
```
* For renditions:
```
gsutil -m cp -r gs://livepeer-verifier-renditions .
```

Specific variations can also be chosen by:
```
gsutil -m cp -r gs://livepeer-verifier-renditions/#Name_of_rendition#/ .
```
Where #Name_of_rendition# is any of the following:

* 1080p_watermark 
* 1080p_watermark-345x114 
* 1080p_watermark-856x856 
* 1080p_vignette 
* 1080p_flip_vertical
* 1080p_rotate_90_clockwise
* 1080p_black_and_white
* 1080p_low_bitrate_4
* 1080p_low_bitrate_8
* 720p
* 720p_watermark
* 720p_watermark-345x114
* 720p_watermark-856x856
* 720p_vignette
* 720p_black_and_white
* 720p_low_bitrate_4
* 720p_low_bitrate_8
* 720p_flip_vertical
* 720p_rotate_90_clockwise
* 480p
* 480p_watermark
* 480p_watermark-345x114
* 480p_watermark-856x856
* 480p_vignette
* 480p_black_and_white
* 480p_low_bitrate_4
* 480p_low_bitrate_8
* 480p_flip_vertical
* 480p_rotate_90_clockwise
* 360p
* 360p_watermark
* 360p_watermark-345x114
* 360p_watermark-856x856
* 360p_vignette
* 360p_black_and_white
* 360p_low_bitrate_4
* 360p_low_bitrate_8
* 360p_flip_vertical
* 360p_rotate_90_clockwise
* 240p
* 240p_watermark
* 240p_watermark-345x114
* 240p_watermark-856x856
* 240p_vignette
* 240p_black_and_white
* 240p_low_bitrate_4
* 240p_low_bitrate_8
* 240p_flip_vertical
* 240p_rotate_90_clockwise
* 144p
* 144p_watermark
* 144p_watermark-345x114
* 144p_watermark-856x856
* 144p_vignette
* 144p_black_and_white
* 144p_low_bitrate_4
* 144p_low_bitrate_8
* 144p_flip_vertical
* 144p_rotate_90_clockwise
