### ISSUE TITLE
Upload OC-SVM model to Google cloud

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#103]
The model at https://storage.googleapis.com/verification-models/verification.tar.xz previously contained the OC-SVM model. At the moment, it contains a combination of a meta model (combining OC-SVM model and a SL model) and a SSIM predictor. We need to fix #102 before the meta model can be used. So, for the time being we should make sure the OC-SVM model is available at the mentioned URL. In the future, we can give different names to different models.

**Comment by ndujar** [comment]
Fixed in e03e4d3
