### ISSUE TITLE
Generation of a metamodel for inference

### ISSUE THREAD

**Issue by ndujar** [livepeer/verification-classifier#15]
With the predictions obtained from all different ML techniques (Supervised and Unsupervised), it is possible to create the input for a more accurate version, a "meta-model".
We need to check:
* Different assembly techniques (averaging, boosting, neural network...)
* Behavior against unseen attacks (those we couldn't think of)
* Continuous re-training process

**Comment by Sorkanius** [comment]
This will include techniques such as bagging, boosting and Neural Networks to combine the models

**Comment by Sorkanius** [comment]
The model is create. We still have to implement it on the CLI.
