### ISSUE TITLE
Feature Selection

### ISSUE THREAD

**Issue by Sorkanius** [livepeer/verification-classifier#18]
Random Forest and gridsearch techniques will be used in order to select which are the features most relevant to the models. We will combine this information with the benchmarking to study the trade off between accuracy and computing time

**Comment by ndujar** [comment]
Output from Random Forest exploration with sklearn feature_importances function:
 	importance 	feature_name
 	0.264271 	temporal_dct-euclidean
 	0.250786 	temporal_gaussian-euclidean
 	0.156383 	size
 	0.098364 	temporal_histogram_distance-euclidean
 	0.090455 	temporal_lbp-euclidean
 	0.089594 	dimension
 	0.040798 	temporal_entropy-euclidean
 	0.009350 	fps
Basically, the ones with the most information are temporal_dct-euclidean, temporal_gaussian-euclidean, size of the video and temporal_histogram_distance-euclidean.
