### ISSUE TITLE
Verification Tool

### ISSUE THREAD

**Issue by j0sh** [livepeer/verification-classifier#2]
### Tool Description

CLI tool to start with. This will allow for various workflows such as scripting, research/experiments, and other ad-hoc usage, in addition to the planned local verification and challenge protocols. For the latter protocols, we can build an API layer on top of the CLI tool later, eg, by invoking the CLI tool from the API server.

Deployment via Docker is OK, especially if there are several "moving parts" needed for a fully working environment (eg, ffmpeg / ffprobe in addition to the verifier). However it would be very helpful to have a mechanism (or documented dependencies) for local builds and development, and some way to locally interact with the Docker node via CLI. Will this be an issue with a non-daemonized tool?

### Inputs
* Reference video(s) and transcoded output(s)
    * Would it help reliability or performance to have the API take a list of segments and process several at once?
* Expected codec, resolution and frame rate

### Outputs
* Classifier result (pass / fail)

Optionally, it may be helpful to have these features (they do not need to be in the very first version of the tool):

* Confidence score.
* Anything else that might be interesting or may aid in analysis, eg the per-frame score. 

Possible example:
```
-i, --input
  Reference video (perhaps comma separated if multiple)
-o, --output
  Transcoded video to check (perhaps comma separated if multiple)
-c, --codec
  Expected codec (but maybe we can just assume it's always H.264 for now)
-s, --size
  Expected resolution
-f, --fps
  Expected frame rate
-b, --bitrate
  Maximum bitrate

livepeer_verifier -i in1.ts,in2.ts -o out1.ts,out2.ts -c h264 -s 640x480 -f 30 -b 500k
```

Should we process all renditions for a given source, or just one at a time? We can also make separate invocations of the tool for each rendition.

### Pre-Processing

Before running the metrics, the tool should pre-process the video:

* If necessary, concatenate list of segments
* Adjust source frame rate to match expected fps 
* Rescale source to match expected resolution
* Also convert source pixel layout to match output pixel layout if metrics require this
* Perform sanity checks on easily checkable properties prior to processing output renditions: check codec, resolution, etc
 
Later on we can check some other properties within the tool such as timestamp alignment or bitrate. Precisely how we do this may be TBD; neural network fodder?

**Comment by yondonfu** [comment]
I think the main important things missing from the CLI at the moment (besides the mentioned optional features like confidence score) are:

- Pass in expected resolution, framerate, bitrate, codec (optional - in the short term likely always going to be the same)
- Check rendition for expected resolution, framerate, bitrate in addition to executing the metrics based classifier

**Comment by ndujar** [comment]
>Pass in expected resolution, framerate, bitrate, codec (optional - in the short term likely always going to be the same). The CLI current just accepts the original video and multiple renditions
Check rendition for expected resolution, framerate, bitrate in addition to executing the metrics based classifier

The PR https://github.com/livepeer/verification-classifier/pull/51 is a first attempt to implement a pre-verification in the API.
The pre-verification parameters are optional for each rendition of the list.

INPUT:
> curl localhost:5000/verify -d '{
"source": "https://storage.googleapis.com/livepeer-verifier-renditions/480p/-3MYFnEaYu4.mp4",
"renditions": [
   {"uri": "https://storage.googleapis.com/livepeer-verifier-renditions/144p_black_and_white/-3MYFnEaYu4.mp4"},
   {"uri": "https://storage.googleapis.com/livepeer-verifier-renditions/144p/-3MYFnEaYu4.mp4",   "resolution":{"height":"144", "width":"256"}, "frame_rate": "24"}
], 
"model": "https://storage.googleapis.com/verification-models/verification.tar.xz"}' 
-H 'Content-Type: application/json'

OUTPUT:

Results: [
{
'https://storage.googleapis.com/livepeer-verifier-renditions/144p_black_and_white/-3MYFnEaYu4.mp4': 
{'uri': 'https://storage.googleapis.com/livepeer-verifier-renditions/144p_black_and_white/-3MYFnEaYu4.mp4', 
'tamper': -1}
}, 
{
'https://storage.googleapis.com/livepeer-verifier-renditions/144p/-3MYFnEaYu4.mp4': 
{'uri': 'https://storage.googleapis.com/livepeer-verifier-renditions/144p/-3MYFnEaYu4.mp4', 
'resolution': {'height': True, 'width': True}, 
'frame_rate': False, 
'tamper': 1}
}
]

Currently, there is no logic associated to the lack of compliance, and the 'tamper' verification parameter is always computed, though it would be easy to avoid it if previous pre-verification parameters would not pass.
