### ISSUE TITLE
Go beyond feature visualization

### ISSUE THREAD

**Issue by Sorkanius** [livepeer/verification-classifier#24]
We could use plotly for visualizing the features in 2D/3D and study how different attacks and assets are spread in their vector space. We can use T-SNE (a more complicated, yet more powerful dimensionality reduction tool). We are already using PCA and random projections, but are not distinguishing between attacks.

**Comment by ndujar** [comment]
T-SNE visualization in 3D (and 2D) shows that the features created are rich enough to make a segmentation between attacks (in red) and correct renditions.

![t-sne-0.gif](https://images.zenhubusercontent.com/5cf0489817221c71b75cc4e4/88ca07aa-3d7d-4981-901b-9e2ee86d3f94)

Note however that:

1.- T-SNE is stochastic (results are not repeatable)
2.- This segmentation is possible thanks to the use of data from the attacks. Ideally, we should be able to project with T-SNE without resourcing to that data to make our model completely agnostic.
