### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by ericxtang** [livepeer/verification-classifier#3]
Hi Guys,

I'm trying to run the tool and seeing some unexpected behavior.

Here is what I have (after running docker):
```
root@7e8a7afe1dcb:/# ls ./data-analysis/data/
trailer_480p.mov  trailer_720p.mov
root@7e8a7afe1dcb:/# python3 src/cli.py "./data-analysis/data/trailer_720p.mov" --renditions ./data-analysis/data/trailer_480p.mov
{}
```

Any ideas of what I'm doing wrong?

**Comment by dionisioC** [comment]
Hi! Thanks for the feedback

We have been doing some refactoring (cleaning up and trying to.make it more versatile) and now there is a new param -m that indicates the metric (We have to update the doc) which is one of the following

'temporal_canny',
        'temporal_difference',
        'temporal_psnr',
        'temporal_mse',
        'histogram_distance',
        'hash_euclidean',
        'hash_hamming',
        'hash_cosine'

So doing:

`python3 src/cli.py "./data-analysis/data/trailer_720p.mov" --renditions ./data-analysis/data/trailer_480p.mov -m temporal_canny`

should work. What I am not sure is if the libraries we are using are .mov friendly as we use mp4.

Let me know if this solves the issue o I have to check something else

**Comment by dionisioC** [comment]
Hi! Thanks for the feedback

We have been doing some refactoring (cleaning up and trying to.make it more versatile) and now there is a new param -m that indicates the metric (We have to update the doc) which is one of the following

'temporal_canny',
        'temporal_difference',
        'temporal_psnr',
        'temporal_mse',
        'histogram_distance',
        'hash_euclidean',
        'hash_hamming',
        'hash_cosine'

So doing:

`python3 src/cli.py "./data-analysis/data/trailer_720p.mov" --renditions ./data-analysis/data/trailer_480p.mov -m temporal_canny`

should work. What I am not sure is if the libraries we are using are .mov friendly as we use mp4.

Let me know if this solves the issue o I have to check something else

**Comment by dionisioC** [comment]
We just updated the documentation so it should be more accurate how to use it.

We have done some tests, and seems to be working as expected, but let us know any issue/doubt

Command
```bash
python3 src/cli.py "./data-analysis/data/1080p/_AN9U4D1Cww.mp4" --renditions ./data-analysis/data/1080p_black_and_white/_AN9U4D1Cww.mp4 --metrics temporal_canny
```
Output
```javascript
{'temporal_canny': '{".\\/data-analysis\\/data\\/1080p\\/_AN9U4D1Cww.mp4":{"Euclidean":0.0},".\\/data-analysis\\/data\\/1080p_black_and_white\\/_AN9U4D1Cww.mp4":{"Euclidean":4.6906685426}}'}
```
Command
```bash
python3 src/cli.py "./data-analysis/data/1080p/_AN9U4D1Cww.mp4" --renditions ./data-analysis/data/1080p_black_and_white/_AN9U4D1Cww.mp4 --metrics temporal_canny --metrics temporal_difference
```
Output
```javascript
{'temporal_canny': '{".\\/data-analysis\\/data\\/1080p\\/_AN9U4D1Cww.mp4":{"Euclidean":0.0},".\\/data-analysis\\/data\\/1080p_black_and_white\\/_AN9U4D1Cww.mp4":{"Euclidean":4.6906685426}}', 'temporal_difference': '{".\\/data-analysis\\/data\\/1080p\\/_AN9U4D1Cww.mp4":{"Euclidean":0.0},".\\/data-analysis\\/data\\/1080p_black_and_white\\/_AN9U4D1Cww.mp4":{"Euclidean":5.4845063655}}'}
```
Command
```bash
python3 src/cli.py "./data-analysis/data/1080p/_AN9U4D1Cww.mp4" --renditions ./data-analysis/data/1080p_black_and_white/_AN9U4D1Cww.mp4 --metrics temporal_canny --metrics temporal_difference --metrics hash_cosine
```
Output
```javascript
{'temporal_canny': '{".\\/data-analysis\\/data\\/1080p\\/_AN9U4D1Cww.mp4":{"Euclidean":0.0},".\\/data-analysis\\/data\\/1080p_black_and_white\\/_AN9U4D1Cww.mp4":{"Euclidean":4.6906685426}}', 'temporal_difference': '{".\\/data-analysis\\/data\\/1080p\\/_AN9U4D1Cww.mp4":{"Euclidean":0.0},".\\/data-analysis\\/data\\/1080p_black_and_white\\/_AN9U4D1Cww.mp4":{"Euclidean":5.4845063655}}', 'hash_cosine': '{".\\/data-analysis\\/data\\/1080p\\/_AN9U4D1Cww.mp4":{"Euclidean":0.0},".\\/data-analysis\\/data\\/1080p_black_and_white\\/_AN9U4D1Cww.mp4":{"Euclidean":4.6398870925}}'}
```
