### ISSUE TITLE
Metrics computation time for different # of frames sampled

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#36]
[This table](https://github.com/livepeer/verification-classifier/issues/35#issuecomment-509639180) provides the TPR/TNR scores achieved for different # of frames sampled. [Previously](https://github.com/livepeer/verification-classifier/issues/7#issuecomment-499905992), we saw that the metrics computation time should decrease linearly as the # of frames used decreases. It would be helpful to have a table with the actual metrics computation time numbers for different # of frames sampled to use as a reference.

**Comment by ndujar** [comment]
Using the table at the top (results for different number of randomly picked frames for all assets in the dataset: 136931 videos), below it is expanded with the respective initialization user time and rendition user time

frames | TPR_test | TNR | auc | f_beta | TPR_train | T_init | T_rend
-- | -- | -- | -- | -- | --
1 | 0.988992 | 0.724256 | 0.856624 | 0.972206 | 0.988220 | 0.322 | 0.365
5 | 0.992514 | 0.713610 | 0.853062 | 0.975021 | 0.986459 | 0.328 | 0.351
10 | 0.992734 | 0.725176 | 0.858955 | 0.975932 | 0.988220 | 0.325 | 0.362
15 | 0.992514 | 0.725027 | 0.858771 | 0.975707 | 0.988220 | 0.344 |  0.372
30 | 0.992074 | 0.725132 | 0.858603 | 0.975282 | 0.988220 | 0.347 | 0.383
60 | 0.992514 | 0.725044 | 0.858779 | 0.975708 | 0.988220 | 0.407 | 0.474
90 | 0.992734 | 0.725211 | 0.858973 | 0.975934 | 0.988220 | 0.415 | 0.474
120 | 0.992734 | 0.724887 | 0.858811 | 0.975915 | 0.988220 | 0.405 | 0.476

**Comment by yondonfu** [comment]
Are the values for `T_init` and `T_rend` the total times (i.e. includes read, decode, feature extraction)? Or are the values just the time for feature extraction?

**Comment by ndujar** [comment]
Values represent total processing time for that part (read, decode and extract features).
It is worth noting that these results were obtained using a downsizing of the frames to 128x72 pixels.

**Recent experiments, however, suggest that higher TNR values can be obtained with a less aggressive downsizing (i.e. 480x270px give a TNR of  87.0%, with only a slightly lower F20 of 97.3%).**

Tables below display **user time** needed for computation with different frame re-sizing (Intel® Core™ i7-8550U CPU @ 1.80GHz × 8, 15,4 GiB RAM) :

frames | WxH | T_init | T_rend | T_tot
-- | -- | -- | -- | --
1 | 128x72 | 0.296 | 0.343 | 0.726
5 | 128x72 | 0.308 | 0.354 | 0.775
10 | 128x72 | 0.359 | 0.335 | 0.996
15 | 128x72 | 0.384 | 0.342 | 0.805
30 | 128x72 | 0.386 | 0.438 | 0.911
60  | 128x72 | 0.423 | 0.496 | 1.009

frames | WxH | T_init | T_rend | T_tot
-- | -- | -- | -- | --
1 | 256x144 | 0.337 | 0.388 | 0.825
5 | 256x144 | 0.402 | 0.398 | 0.896
10 | 256x144 | 0.388 | 0.457 | 0.928
15 | 256x144 | 0.431 | 0.440 | 0.973
30 | 256x144 | 0.441 | 0.461 | 0.997
60  | 256x144 | 0.538 | 0.582 | 1.208

frames | WxH | T_init | T_rend | T_tot
-- | -- | -- | -- | --
1 | 480x270 | 0.395 | 0.464 | 0.943
5 | 480x270 | 0.403 | 0.455 | 0.939
10 | 480x270 | 0.434 | 0.473 | 1.006
15 | 480x270 | 0.464 | 0.512 | 1.061
30 | 480x270 | 0.501 | 0.535 | 1.121
60  | 480x270 | 0.631 | 0.692 | 1.408

frames | WxH | T_init | T_rend | T_tot
-- | -- | -- | -- | --
1 | 960x540 | 0.475 | 0.511 | 1.126
5 | 960x540 | 0.539 | 0.607 | 1.243
10 | 960x540 | 0.571 | 0.609 | 1.265
15 | 960x540 | 0.662 | 0.706 | 1.494
30 | 960x540 | 0.944 | 0.942 | 1.976
60  | 960x540 | 1.349 | 1.386 | 2.875

frames | WxH | T_init | T_rend | T_tot
-- | -- | -- | -- | --
1 | 1280x720 | 0.647 | 0.686 | 1.432
5 | 1280x720 | 0.755 | 0.807 | 1.670
10 | 1280x720 | 0.909 | 0.954 | 1.948
15 | 1280x720 | 1.021 | 1.061 | 2.184
30 | 1280x720 | 1.426 | 1.482 | 2.995
60  | 1280x720 | 2.276 | 2.361 | 4.722

frames | WxH | T_init | T_rend | T_tot
-- | -- | -- | -- | --
1 | 1920x1080 | 0.879 | 0.895 | 1.858
5 | 1920x1080 | 1.082 | 1.056 | 2.226
10 | 1920x1080 | 1.353 | 1.363 | 2.803
15 | 1920x1080 | 1.677 | 1.707 | 3.473
30 | 1920x1080 | 2.818 | 2.814 | 5.716
60  | 1920x1080 | 4.819 | 5.051 | 9.955
