### ISSUE TITLE
Verifier node prototype

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#40]
## Background

The first step of an effort to integrate the verification classifier in this repo with a LP broadcaster node (so that it can verify renditions returned by a LP orchestrator node) is to create a simple verification API that a LP broadcaster can use. By exposing verification functionality with an API we can keep the LP broadcaster code separate from the verification classifier code for now.

## API Proposal

At the moment, the CLI tool (housed in this repo) itself is pretty slim since the bulk of the functionality is imported from other Python modules (i.e. the video asset processor used to generate metrics). This functionality could be incorporated into a simple HTTP server. This server can then be run inside a Docker container (there is already a Docker image for the CLI) to eliminate any Python dependency headaches.

I think creating a JSON-RPC HTTP API is the simplest approach (but a REST HTTP API would work as well). 

The initial API specification:

**verify**

Returns the verification results for a set of renditions and their original source.

**Parameters**

1. `Object` - The verification request object
- `source`: `string` - The URI that can be used to download the input segment. The verifier can infer how to down the segment based on the schema of the URI (i.e. download via HTTPS if the URI has a `https://` prefix). If the verifier does not support the schema of the URI or if it is missing, the verifier will look for the data locally
- `renditions`: `array Rendition` - An array of rendition objects that contain rendition URIs that can be used to download the rendition segment data. The rendition URIs are nested in a object to allow for future addition of fields that can indicate expected values for pre-verification checks (i.e. expected bitrate, framerate, resolution, etc.)

**Example Parameters**

```
params: [{
    "source": "http://127.0.0.1/stream/abcd/5.ts",
    "renditions": [
        {
            "uri": "http://127.0.0.1/stream/abcd/P720p30fps4x3/5.ts"
        },
        {
            "uri": "http://127.0.0.1/stream/abcd/P720p60fps16x9/5.ts"
        }
    ]
}]
```

**Returns**

An object that indicates whether each rendition passed/failed verification.

**Example**

*Request*

```
curl --data '{"method":"verify","params":[{}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
```

Note: Actual parameters are omitted in the example request above.

*Response*

```
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "http://127.0.0.1/stream/abcd/P720p60fps16x9/5.ts": true,
        "http://127.0.0.1/stream/abcd/P720p30fps4x3/5.ts": false
    }
}
```

In theory, video segments could be fetched from a variety of storage locations - LP nodes have the option of specifying how they want to store data (see the [go-livepeer README](https://github.com/livepeer/go-livepeer#using-amazon-s3-for-storing-streams-data)). But a first pass implementation of the verifier node can just support looking for files locally (the scenario where the API server is running on the same machine as the broadcaster). In a subsequent iteration, support for fetching data from different storage locations can be added.

**Rendition**

This message will be fairly simple initially:

```
{
    "uri": ...
}
```

In subsequent iterations, it could include additional fields:

```
{
    "uri": ...
    "resolution": {
         "width": 960,
          "height": 720
     },
     "framerate": 30,
     "bitrate": "3500k"
}
```

## Looking Ahead: Next Steps

The most barebones verifier node implementation could just expose the API mentioned above and be able to respond to HTTP requests (i.e. via curl).

Possible next steps afterwords (in suggested order):

1. Enable pre-verification checks with expected values specified in the API request (i.e. expected bitrate, framerate, resolution, etc.)
2. Implement an initial integration with a LP broadcaster. Rough sketch of what could be included:
-  Broadcaster can be started with a CLI flag `-verifier` that specifies how to connect with the verifier
- Broadcaster can be started with a CLI flag `-verifySampleRate` that specifies how often to verify results received from an orchestrator
- Broadcaster sends a request to the verifier for each sampled result
- Broadcaster logs the response

Beyond these steps we can explore writing the verification pass/fail rates for orchestrators into a broadcaster's DB and supporting additional storage locations. After that, we can consider the possibility of using verification pass/fail rates to influence orchestrator selection, but it would be helpful to gather data on verifier performance prior to that.

**Comment by j0sh** [comment]
> This functionality could be incorporated into a simple HTTP server

To clarify, this HTTP server would just invoke the CLI? If verification of a sample currently cannot be executed via a single CLI command, maybe that should be done first.

> storageType: int32 - An integer indicating which storage type is being used for video segments i.e. 0 = Local, 1 = S3 (Amazon S3), 2 = GS (Google Storage), 3 = IPFS, etc.

Can we use strings rather than numeric values here? Could probably also be simplified to just  "Local" or "URL". Likely could be made entirely optional as well, because I think it should be possible to infer the storage type from the URI string alone (eg, missing scheme == local file)

> Beyond these steps we can explore writing the verification pass/fail rates for orchestrators into a broadcaster's DB

I'd also consider storing the results on the verifier itself, which makes coordination easier for centralized verification setups. I have a preference for implementing this prior to any broadcaster-local storage.

**Comment by yondonfu** [comment]
> To clarify, this HTTP server would just invoke the CLI?

That is one option. The approach that I'm thinking of is to have a Python server wrap most of the logic in [this function](https://github.com/livepeer/verification-classifier/blob/master/cli/cli.py#L21) which is invoked by the CLI tool. This approach doesn't seem like it would require much more work than directly invoking the CLI and it also avoids running the CLI tool as a subprocess.

> If verification of a sample currently cannot be executed via a single CLI command, maybe that should be done first.

That should be possible right now - see the [README](https://github.com/livepeer/verification-classifier/tree/master/cli#3--usage) for the CLI.

While we can certainly invoke the CLI from the Livepeer node, I think the benefit of abstracting away the verifier by only exposing the LP broadcaster to an API with a configured endpoint to send requests to offers a cleaner separation between the verification-classifier and LP code. Furthermore, a simple HTTP server could not only be run on the same machine as a LP broadcaster node, but it could be run on a separate machine as well if needed. What do you think?

> Can we use strings rather than numeric values here? Could probably also be simplified to just "Local" or "URL". Likely could be made entirely optional as well, because I think it should be possible to infer the storage type from the URI string alone (eg, missing scheme == local file)

Good point - the verifier doesn't need to know the actual storage provider, it just needs a URI string and as long as it supports the schema (i.e. HTTP) it will be able to fetch the data. Modified the original post to omit the `storageType` field and added a note about defaulting to looking for a local file if the schema is not supported or is missing.

> I'd also consider storing the results on the verifier itself, which makes coordination easier for centralized verification setups. I have a preference for implementing this prior to any broadcaster-local storage.

I agree that we should consider storing the results on the verifier. However, it is worth noting that if the purpose of storing results on the verifier is so that broadcasters can ask the verifier about the success/failure rate of a particular orchestrator then the architecture for a centralized verifier node is a bit different than a verifier node that a broadcaster operator runs on its own. The former requires the broadcaster to tell the verifier which orchestrator the verification request is for and to also provide the orchestrator's signatures for authentication (so that the verifier can confirm that the orchestrator actually produced the data). The latter does not require orchestrator identity or authentication via signatures because the operator running the verifier is the only one that is using the verification results.

**Comment by j0sh** [comment]
> abstracting away the verifier by only exposing the LP broadcaster to an API with a configured endpoint to send requests to offers a cleaner separation between the verification-classifier and LP code. 

Absolutely - I wasn't suggesting *not* to do this, only that the API just becomes a HTTP frontend to the CLI.

FWIW, the [Python CLI function](https://github.com/livepeer/verification-classifier/blob/master/cli/cli.py#L21) seems like it does a lot by itself. If anything requires changes in that area, then the code would need to be updated in two places - both the CLI and API.

As a first pass, running a subprocess doesn't seem like an issue. In fact, it seems like a nicer way to get a more robust separation between the verifier implementation and the API. Eg, we get to run each verification in its own Python process (avoids GIL around concurrent verifications on a shared process), the API service doesn't have to be in the same language and can be further optimized separately, etc.

> The former requires the broadcaster to tell the verifier which orchestrator the verification request is for and to also provide the orchestrator's signatures for authentication (so that the verifier can confirm that the orchestrator actually produced the data)

Good point, those would need to be added to the B's request object as well.

**Comment by yondonfu** [comment]
> As a first pass, running a subprocess doesn't seem like an issue. In fact, it seems like a nicer way to get a more robust separation between the verifier implementation and the API

Good points especially avoiding the GIL around concurrent verifications on a shared process without any additional effort. I think it is reasonable to just run the CLI as a subprocess as a first pass. In summary, the first pass for this prototype will involve:

- Implementing a HTTP server that exposes the API specified in the original post
- The HTTP server can run the CLI as a subprocess

After this first pass, we can check-in about next steps such as whether the verifier should by default store verification results (which likely would require the API request object to include orchestrator identity and authentication fields (i.e. signatures)).

**Comment by yondonfu** [comment]
Following up on the previous comment - as a next step, I think it would be useful to associate an orchestrator ID with each verification request and add storage for the verifier.

In practice, the orchestrator will likely be an ETH address, but from the verifier's standpoint the ID is just a string so we can probably skip strict enforcement of an ID format for now. The purpose of this ID is to be able to keep track of verification results for an orchestrator over time.

The request would look something like this:

```
{
    "orchestratorID": "foo",
    "source": ...,
    "renditions: [...],
    "model": ...
}
```

In order to keep track of verification results for an orchestrator over time, the verifier will need to persist results in storage. An alternative would be for the broadcaster (which would query the verifier's API) to keep results in its own storage, but keeping verification results separate from the broadcaster's storage has a few benefits as already mentioned in this thread as well as maintaining a separation of concerns between the broadcaster and the verifier. At the minimum, the verifier can keep track of pass/fail (or a quality score if #46 is implemented) records for an orchestrator - this could allow for the calculation of an average pass/fail rate (or an average quality score). Perhaps it also makes sense to maintain a pointer to the persisted source and rendition data for forensics later on.

**Comment by yondonfu** [comment]
The prototype is done and I created #56 to track the additional feature mentioned above so closing this issue.
