### ISSUE TITLE
Verifier storage for requests associated with orchestrator ID

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#56]
Now that a verifier API is implemented, it could be useful to associate an orchestrator ID with each verification request and add storage for the verifier.

In practice, the orchestrator will likely be an ETH address, but from the verifier's standpoint the ID is just a string so we can probably skip strict enforcement of an ID format for now. The purpose of this ID is to be able to keep track of verification results for an orchestrator over time. I think we can omit a signature from the orchestrator (used to authenticate the provided data) for the time being as it is not as crucial if the verifier is only used by a single broadcaster - if a central verifier setup is needed then we can look into incorporating the signature.

The request would look something like this:

```
{
    "orchestratorID": "foo",
    "source": ...,
    "renditions: [...],
    "model": ...
}
```

In order to keep track of verification results for an orchestrator over time, the verifier will need to persist results in storage. An alternative would be for the broadcaster (which would query the verifier's API) to keep results in its own storage, but keeping verification results separate from the broadcaster's storage has a few benefits as already mentioned in this thread as well as maintaining a separation of concerns between the broadcaster and the verifier. At the minimum, the verifier can keep track of pass/fail (or a quality score if #46 is implemented) records for an orchestrator - this could allow for the calculation of an average pass/fail rate (or an average quality score). Perhaps it also makes sense to maintain a pointer to the persisted source and rendition data for forensics later on. Alternatively, the verifier can just keep track of metrics calculated for each verification request that could also be used for forensics and also model retraining (?).

**Comment by ndujar** [comment]
> In order to keep track of verification results for an orchestrator over time, the verifier will need to persist results in storage. An alternative would be for the broadcaster (which would query the verifier's API) to keep results in its own storage, but keeping verification results separate from the broadcaster's storage has a few benefits as already mentioned in this thread as well as maintaining a separation of concerns between the broadcaster and the verifier. At the minimum, the verifier can keep track of pass/fail (or a quality score if #46 is implemented) records for an orchestrator - this could allow for the calculation of an average pass/fail rate (or an average quality score). Perhaps it also makes sense to maintain a pointer to the persisted source and rendition data for forensics later on. Alternatively, the verifier can just keep track of metrics calculated for each verification request that could also be used for forensics and also model retraining (?).

In [d89eaf](https://github.com/livepeer/verification-classifier/commit/fcb50414081452a755c7876c5139d3b974d89eaf) persistent logs have been enabled for the verifier. 
Currently, only the output of the API call is stored in the verifications.log file, whereas operational logas are stored in ops.log.
The corresponding computed metrics could also be sent to a metrics.log in a future, once the retraining pipeline is made clear.
