### ISSUE TITLE
Model URL as API startup arg

### ISSUE THREAD

**Issue by j0sh** [livepeer/verification-classifier#63]
Should the `model` URL that is currently provided as a request argument be supplied as an API startup argument instead?

I understand that the current method makes it easier to quickly test model iterations without restarting the API, but the potential to pass in an arbitrary model seems problematic if we were to collect data from the verifier from the public. At the very least, setting the model at API startup time would ensure consistency in data collection and analysis.

Also, the model that was used for a given verification should probably be recorded in the logs.

**Comment by yondonfu** [comment]
I think another benefit of specifying the model on startup is that the verifier can cache the model on startup rather than fetching the model and caching it when it receives the first request.

**Comment by ndujar** [comment]
> Should the model URL that is currently provided as a request argument be supplied as an API startup argument instead?
Initially the idea was to enable the possibility of A/B testing of re-trained models, and also make easier the choice of more or less restrictive models in different trust environments. However, this is perhaps looking a bit too much ahead and might not be necessary at all.

> I think another benefit of specifying the model on startup is that the verifier can cache the model on startup rather than fetching the model and caching it when it receives the first request.
In the current implementation, this is quite the case, as the verifier checks the existence of a tmp/model folder in the docker image.
This means that model download only happens the first time an API call happens.

> Also, the model that was used for a given verification should probably be recorded in the logs.
[Done](https://github.com/livepeer/verification-classifier/commit/6b2c662fbab723ac2d67f5f9f04b5dcf3ab0f267)

**Comment by yondonfu** [comment]
Closed by #114
