### ISSUE TITLE
Classifier Name

### ISSUE THREAD

**Issue by j0sh** [livepeer/verification-classifier#65]
In the process of integrating this classifier, I wasn't sure what to call it within the Livepeer codebase :) This name would also be exposed to users via CLI flags, documentation, etc.

In my head, I've been calling this the "Epic Labs classifier" with the CLI / configuration flags prefixed by something like `-epicClassifier` but just wanted to check if you had other thoughts or preferences about this related to branding, or perhaps a cool internal code name that you'd like to see used, etc.

**Comment by ndujar** [comment]
-epicClassifier sounds good to me :)
