### ISSUE TITLE
Create a QoE predictor

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#71]
Given a QoE dataset (#66), a QoE predictor can be created. This predictor can accept as input the desired resolution and bitrate of a transcoded video. The desired resolution can be used to select a corresponding QoE curve - the points on the curve represent the expected QoE score for a particular bitrate level. So, once a curve is selected, the desired bitrate can be used to determine the expected QoE score of the transcoded video. This expected QoE score can then be used when verifying received transcoded video.

**Comment by ndujar** [comment]
A CatBoost regressor model has been trained using data generated in #66.
Accuracy metrics of the model are:
![image.png](https://images.zenhubusercontent.com/5cf0489817221c71b75cc4e4/e301a650-2d6a-4d89-96cf-5db1a9b23ff5)
It allows for the prediction of SSIM values at the end of the verification process.
