### ISSUE TITLE
Updated performance benchmarking when extracting QoE metrics

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#72]
#71 will result in a QoE predictor that can be used to determine the expected QoE score which can be used when verifying transcoded video. In order to check that the transcoded video meets the expected QoE score, QoE values will need to be extracted from the frames of the video. It will be helpful to determine what the extra computational cost will be for extracting these QoE values (i.e. SSIM or PSNR). A good first step would be to directly extract the QoE values and determining the associated cost. An interesting second step if the initial cost feels high would be to see if we can use feature values already being extracted for tamper detection to compute the QoE values (for example, the Gaussian is already computed for tamper detection and this is a necessary value for computing SSIM).

**Comment by ndujar** [comment]
With the current configuration, QoE metrics don't need to be evaluated at run time. Their values are inferred directly from the tampering features using a pre-trained model.
