### ISSUE TITLE
Article V

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#75]
An interesting topic for article V is the [comparison study of the tamper verifier vs. traditional QoE metrics](https://github.com/livepeer/verification-classifier/issues/68) which shows that traditional QoE metrics (i.e. SSIM, PSNR) are not well suited for tamper detection and that the tamper verifier (based on a OCSVM) is necessary for tamper detection.

**Comment by ndujar** [comment]
Find the article published here:
https://medium.com/@epiclabs.io/machine-learning-for-video-transcoding-verification-in-livepeers-ecosystem-ii-7b936f64da61
