### ISSUE TITLE
Identify reason for seemingly incorrect SSIM values

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#76]
When calculating SSIM for a set of videos, curves for the scores were graphed with the y-axis = score and x-axis = size of the video. The shape of the curves were as expected for certain videos, but different  for other videos (inverted). This raises suspicions that the SSIM calculation is done incorrectly. Possible reasons:

- Frames are currently downscaled instead of upscaled
- Random sampling influence?

It'll be helpful to understand the reason for the weird SSIM score distribution and what the source of the miscalculation is. This is a blocker for #72

**Comment by j0sh** [comment]
Curious, which SSIM implementation are we talking about here?

**Comment by yondonfu** [comment]
@ndujar can provide a better explanation, but here is my understanding: 

I believe its the temporal SSIM implementation that calculates SSIM on a [per frame basis](https://github.com/livepeer/verification-classifier/blob/master/scripts/asset_processor/video_metrics.py#L270) over a set of frames where the frames are randomly sampled, but also [downscaled](https://github.com/livepeer/verification-classifier/blob/e4dd52de049f5166e74cabdd4cf583e70067c204/scripts/modeling_toolbox/metric_processor.py#L162).

To clarify, I think the current suspects are the downscaling of frames and random sampling of frames as opposed to the actual SSIM implementation itself which comes from [skimage](https://github.com/livepeer/verification-classifier/blob/master/scripts/asset_processor/video_metrics.py#L10).

This is a screenshot of the distribution of temporal PSNR values for the dataset from the recent presentation:

![Screen Shot 2019-11-01 at 12 21 58 PM](https://user-images.githubusercontent.com/5933273/68039309-3d9b4c00-fca2-11e9-9470-987b302cd8f9.png)

This is a screenshot of the distribution of temporal SSIM values for the dataset from the recent presentation:

![Screen Shot 2019-11-01 at 12 22 01 PM](https://user-images.githubusercontent.com/5933273/68039313-412ed300-fca2-11e9-8a07-4eff32dcd18b.png)

**Comment by ndujar** [comment]
> Curious, which SSIM implementation are we talking about here?

As @yondonfu correctly points out, the implementation used is that of [skimage](https://github.com/livepeer/verification-classifier/blob/e4dd52de049f5166e74cabdd4cf583e70067c204/scripts/asset_processor/video_metrics.py#L10).
However, prior to computing the metrics we are resizing the frames in both the original and the rendition [here](https://github.com/livepeer/verification-classifier/blob/e4dd52de049f5166e74cabdd4cf583e70067c204/scripts/asset_processor/video_asset_processor.py#L109). This is made for the sake of faster computation, but it is likely to affect the output of the QoE metrics, as the downsizing interpolation (cv2.INTER_LINEAR) adds some extra noise that needs to be accounted for. We need to evaluate this as well, and see to what extent this is affecting.
Yet another more plausible suspect is the downscaling we are making to the actual mean value in the [rescale_to_resolution()](https://github.com/livepeer/verification-classifier/blob/e4dd52de049f5166e74cabdd4cf583e70067c204/scripts/asset_processor/video_asset_processor.py#L337) function. @yondonfu  is addressing it correctly in the metrics-processor module but in the current implementation it has been included in the actual creation of the set of features, likely distorting the results.

**Comment by ndujar** [comment]
A number of fixes have been needed to solve this problem:
1.- The problem at large was originated in a shifting of frames at encoding time due to audio tracks misalignment. All renditions have been re-transcoded and metrics extracted successfully.
2.- A HD version of each randomly sampled frame is now created in the VideoAssetProcessor class, in addition to the 480x270px used for verification. This allows for a more accurate evaluation of the QoE metrics, as there is no fading of artifacts due to interpolation.
3.- SSIM and PSNR have been excluded from the post-process downscaling as they have no use in the verification model as features.
