### ISSUE TITLE
Save parameter JSON files with pickled models

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#8]
Reposting idea by @Sorkanius from last Friday's call.

We can save a JSON file with each pickled model that contains parameter information for the model i.e. true positive rate, true negative rate, false negative rate (this one would be particularly useful since we want to avoid false negatives as much as possible on the Livepeer network), etc.

**Comment by Sorkanius** [comment]
Already done with Unsupervised Learning notebook. We will unify both learning methods in the pipeline we will create.

**Comment by Sorkanius** [comment]
This should also include saving the matrices used in dimensionality reduction and the standardization values
