### ISSUE TITLE
Generate a BRISQUE model

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#81]
We can create a model based on [BRISQUE](https://www.learnopencv.com/image-quality-assessment-brisque/) data.

Since BRISQUE only relies on the source video, a broadcaster can use this data to forecast the distortion curve for a particular rendition before receiving the result. This would enable a broadcaster to determine the expected QoE (i.e. SSIM/PSNR) score for a source segment when targeting a specific resolution and bitrate and the inferred QoE score of a rendition can be compared against this expected score.

**Comment by ndujar** [comment]
I have created the PR in ebda446326f6aa85bae0c744c7650b6743bd9cb5

This PR adds the code for training and evaluating a model for prediction of rate-distortion curves (with SSIM only) given a source video at 1080p.
Predictions are made from the BRISQUE parameters extracted from a random number of frames in the source asset.
![image.png](https://images.zenhubusercontent.com/5cf0489817221c71b75cc4e4/c0651137-5dd3-4c28-8395-627338963036)
At the time of this PR, average accuracy is:

    MAPE = 0.0164 for SSIM predictions
    MAPE = 0.0460 for bitrate predictions
