### ISSUE TITLE
Create training dataset with 720p videos

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#87]
At the moment, the training dataset only contains 1080p source videos. We want to create a training dataset with 720p videos in order to train a tamper model that performs well when the input video is 720p. One way to create this training dataset is to rescale the existing 1080p source videos into 720p videos. If we use this approach, then the rescaling procedure can likely be reused to generate training datasets for other resolutions as well in the future.

**Comment by ndujar** [comment]
Dataset is ready, with feature values obtained from renditions located under livepeer-verifier-renditions  bucket.
The dataset values are are kept in the datastore namespace livepeer-verifier-training, under the features-input-rescaling.
