### ISSUE TITLE
Create a OCSVM tamper model trained on 720p videos

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#88]
We want to have a OCSVM tamper model trained on 720p videos so that a broadcaster can properly verify input video that is 1080p OR 720p. The broadcaster can check the input resolution and if it is 1080p it will use the OCSVM tamper model trained on 1080p videos and if it is 720p it will use the OCSVM tamper model trained on 720p videos.

**Comment by ndujar** [comment]
Using the dataset created in https://github.com/livepeer/verification-classifier/issues/87, a model has been trained so it can be used interchangeably with the current one based on 1080p. It must be noted that the 720p dataset omits the following attacks (hence reducing its accuracy metrics):
* low_bitrate_4
* low_bitrate_8
* rotate_90_clockwise
* flip_vertical
* 1080p related ones
* 720p related ones

Accuracy results are:
* TPR: 0.994
* TNR: 0.743
* F-20: 0.979

With the same set of attacks, the 1080p (current) dataset has:
* TPR: 0.995
* TNR: 0.762
* F-20: 0.981

When data from the 720p dataset is fed to the OCSVM trained on the 1080p datset, results are:
* TPR: 0.994
* TNR: 0.772
* F-20: 0.980
 
After careful observation and comparison, there seems to be no significant difference between models trained with one or another dataset.
The assumption that different source resolutions affects the metrics must be revisited.
Table below displays the ratios between features of both datasets:

 	|aggregator|size_dimension_ratio|temporal_dct-mean|temporal_gaussian_mse-mean|temporal_gaussian_difference-mean|temporal_threshold_gaussian_difference-mean
|--- |--- |--- |--- |--- |--- |
|count|1.002060|0.997149|0.999448|1.006470|1.105759|
|mean|0.997859|1.012072|1.042242|1.010197|1.086164|
|std|1.001893|0.941064|0.997475|1.092844|1.326059|
|25%|1.002134|0.992464|0.979570|1.037281|1.166553|
|50%|1.002048|0.967067|0.946982|0.973144|1.145948|

**Comment by yondonfu** [comment]
> After careful observation and comparison, there seems to be no significant difference between models trained with one or another dataset.

Interesting. This would seem to contradict the low success rate when transcoding a 720p source as described in #84 

We'll do some additional benchmarking with the verifier running alongside a broadcaster node using both a 720p and 1080p source to double check if there is a significant difference in success rate when using a 720p vs. 1080p source.

**Comment by yondonfu** [comment]
Here are the results of some benchmarking with a broadcaster that verifies each transcoded result using the verifier. The model used is at https://storage.googleapis.com/verification-models/verification.tar.xz. The broadcaster is running on an AWS t2.medium instance and the verifier is running on an AWS t2.xlarge instance. The broadcaster is using a shared remote volume with the verifier mounted using sshfs.

The results were gathered by:

- Running 3 trials. Trial #1 uses a [720p source](https://storage.googleapis.com/lp_testharness_assets/official_test_source_2s_keys_24pfs.mp4). Trial #2 and #3 use a [1080p source](https://storage.googleapis.com/lp_testharness_assets/bbb_sunflower_1080p_30fps_normal_t02.mp4)
- Segments were transcoded by various orchestrators on the Rinkeby public testnet
- For each trial, grepping for the results of verification: `cat broadcaster.log | grep Verification >> verification.log`
- Parsing the `verification.log` files for duration (to calculate the average verification time) and for errors (to determine if tampering was detected)

Example output of the verification log file:

```
I0109 18:00:51.943739   23314 epic.go:160] Verification complete manifestID=foo seqNo=305 err=<nil> dur=7.180480006s
I0109 18:00:51.944429   23314 epic.go:160] Verification complete manifestID=foo seqNo=301 err=<nil> dur=7.303927711s
I0109 18:00:55.849183   23314 epic.go:160] Verification complete manifestID=foo seqNo=306 err=<nil> dur=9.500830005s
I0109 18:00:55.849993   23314 epic.go:160] Verification complete manifestID=foo seqNo=299 err=Tampered dur=8.472327597s
I0109 18:00:57.043900   23314 epic.go:160] Verification complete manifestID=foo seqNo=292 err=Tampered dur=9.442159904s
I0109 18:00:57.044763   23314 epic.go:160] Verification complete manifestID=foo seqNo=308 err=<nil> dur=5.718462683s
I0109 18:00:57.045165   23314 epic.go:160] Verification complete manifestID=foo seqNo=309 err=<nil> dur=3.020089264s
I0109 18:00:57.045673   23314 epic.go:160] Verification complete manifestID=foo seqNo=307 err=<nil> dur=5.454858815s
I0109 18:00:59.057509   23314 epic.go:160] Verification complete manifestID=foo seqNo=311 err=<nil> dur=1.284687701s
```

**Trial 1: 720p source -> 240p, 360p**

```
Total requests:  584
Tampered:  500
Non-tampered:  84
Success rate:  0.14383561643835616
Average verification time: 2.6294349272808244 seconds
```

**Trial 2: 1080p source -> 240p, 360p**

```
Total requests:  338
Tampered:  39
Non-tampered:  299
Success rate:  0.8846153846153846
Average verification time: 1.6748563214497034 seconds
```

**Trial 3: 1080p source -> 240p, 360p, 720p**

```
Total requests:  365
Tampered:  97
Non-tampered:  268
Success rate:  0.7342465753424657
Average verification time: 3.910823315238357 seconds
```

**Comment by ndujar** [comment]
Tried the provided samples in order to replicate the results.
One thing I have noted is that videos have different lengths, and in both cases they are probably too long (10'35'' for 1080p sample and 9'56'' for the 720p).
Although it has not been calculated how chunk length affects predictions, it should be limited to 2'-4'.
From the samples provided, I have generated four renditions:
Short chunks of 8s:
`ffmpeg -i bbb_sunflower_1080p_30fps_normal_t02.mp4 -ss 00:00:03 -t 00:00:08 -async 1 -c:v libx264 -vf -c:a copy 1080p.mp4`
`ffmpeg -i official_test_source_2s_keys_24pfs.mp4 -ss 00:00:03 -t 00:00:08 -async 1 -c:v libx264 -c:a copy 720p.mp4`

Rescaled renditions at 360p:
`ffmpeg -i 1080p.mp4 -c:v libx264 -vf scale=-2:360 -c:a copy 1080-360p.mp4`
`ffmpeg -i 720p.mp4 -c:v libx264 -vf scale=-2:360 -c:a copy 720-360p.mp4`

After 20 runs of the verifier, all calls return a true positive for both 1080p and 720p renditions:
Sample call:
`curl localhost:5000/verify -d '{"source": "stream/sources/720p.mp4",  "renditions": [{"uri": "stream/sources/720-360p.mp4"}],"orchestratorID": "foo", "model": "https://storage.googleapis.com/verification-models/verification.tar.xz"}' -H 'Content-Type: application/json'`
Sample result:
`{"model":"https://storage.googleapis.com/verification-models/verification.tar.xz","orchestrator_id":"foo","results":[{"audio_available":true,"audio_dist":0.0,"tamper":0.365392,"uri":"stream/sources/720-360p.mp4","video_available":true}],"source":"stream/sources/720p.mp4"}
`
A possible explanation is that too long chunks have too much variation and the amount of sampled frames is insufficient for an accurate prediction.

**Comment by yondonfu** [comment]
> One thing I have noted is that videos have different lengths, and in both cases they are probably too long (10'35'' for 1080p sample and 9'56'' for the 720p).

Both the 1080p source and 720p source were segmented by the broadcaster into ~2s segments and each request to the verifier was for a single ~2s source segment.

**Comment by ndujar** [comment]
> Both the 1080p source and 720p source were segmented by the broadcaster into 2s segments and each request to the verifier was for a single 2s source segment.

In the experiments detailed above, the success rate is as expected using the current model, so the length of the chunks seems not to be the issue, given that the broadcaster is supplying 2s segments.
It would be very helpful to have access to a few samples of the sources and renditions passed to the verifier, as well as the (ffmpeg?) commands used.
Could it be that the command used is making something strange with the GOP in the generation of the 720p renditions?
Is it possible to extract also the distance to the decision function of the OCSVM from the logs, not only the duration?

**Comment by yondonfu** [comment]
> It would be very helpful to have access to a few samples of the sources and renditions passed to the verifier

I'll re-run the experiments and get samples for the sources and renditions passed to the veriifer.

> as well as the (ffmpeg?) commands used.

The renditions were transcoded by Livepeer orchestrator nodes on the public testnet (the node don't use the `ffmpeg` binary directly, but they do use the `ffmpeg` C libraries). I'll also try to get information on which orchestrator nodes transcoded which renditions.

> Is it possible to extract also the distance to the decision function of the OCSVM from the logs, not only the duration?

Will make sure to grab this data when re-running the experiments as well.

**Comment by ndujar** [comment]
The following experiments were done, supporting the hypothesis of the problem being in the change of framerate, not in the change of resolution:

DOWNSAMPLING (30fps -> 25fps)
- ffmpeg command (same as before):
 ffmpeg -re -i bbb_sunflower_1080p_30fps_normal_t02.mp4 -vcodec libx264 -b:v 1000k -x264-params keyint=60:min-keyint=60 -acodec copy -f flv rtmp://localhost:1935/movie 

- Number of verifications (720p + 360p + 240p): 276
- Number of false negatives: 12
- TPR: 0.956

UPSAMPLING (24fps -> 30fps)
- ffmpeg command (different source, with 24fps):
 ffmpeg -re -i official_test_source_2s_keys_24pfs.mp4 -vcodec libx264 -b:v 1000k -x264-params keyint=60:min-keyint=60 -acodec copy -f flv rtmp://localhost:1935/movie 

- Number of verifications (720p + 360p + 240p): 585
- Number of false negatives: 200
- TPR: 0.658
