### ISSUE TITLE
Add 'host' and 'port' startup flags

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/verification-classifier#91]
For a setup within a docker network it would be good to have the ability to specify the host and port to run on when starting up the verifier. 

These values are currently hardcoded to be `localhost:5000`

**Descibe the solution you'd like**
A  `-host` and `-port` flag to specify the host and port for the verification classifier server to listen on.

eg. `python api/api.py -host verifier -port 3005` will have the verification endpoint accessible at `http://verifier:3005/verify`

**Comment by cyberj0g** [comment]
Added in [this PR](https://github.com/livepeer/verification-classifier/pull/114).

**Comment by yondonfu** [comment]
Closed by #114
