### ISSUE TITLE
Investigate how to handle different framerate in source and rendition

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#93]
When the framerate in the source is different from the framerate in the rendition, the frames in the source and renditions become misaligned [1]. The verifier is not capable of handling this situation right now and as a result, the extracted metrics are distorted and the verifier will likely believe the rendition is tampered.

We need to investigate ways to ensure that the metrics processor is supplied with the right frames.

[1] There will be cases where a transcoding job involves changing the framerate in the renditions from the framerate in the source

**Comment by ndujar** [comment]
After a lot of research and brain racking, the conclusion is that this problem can only be solved if the transcodification process outputs a list of pairwise correspondences between source frames and rendition frames.
One way to do it is by requiring ffmpeg to output the list of duplicated / dropped frames from the vf filter:
Example:
`ffmpeg -i bbb-30fps_trimmed.mp4 -vf fps=25 bbb-25fps_trimmed.mp4 -y -loglevel debug > downsample.txt 2>&1`

The example above generates a .txt file that can be later on parsed (by the verifier?) to obtain the indexes of the duplicated / added frames:

> [Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 2 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 8 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 14 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 20 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 26 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 32 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 38 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 44 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 50 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 56 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 62 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 68 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 74 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 80 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 86 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 92 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 98 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 104 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 110 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 116 1 times
[Parsed_fps_0 @ 0x564d59489c40] Duplicated frame with pts 122 1 times

From which the verifier can univocally construct a complete list of frames and correspondences between source and rendition.
The transcoder has no incentive in cheating on this list, as the random sampling happens after construction of the list. In the case of giving wrong indices, the result will be a negative evaluation from the verifier.

**Comment by yondonfu** [comment]
Closed by #111
