### ISSUE TITLE
Experiment with taking the nearest frame to a timestamp instead of highest nearest

### ISSUE THREAD

**Issue by yondonfu** [livepeer/verification-classifier#97]
We have experimented with sampling a timestamp and then taking the highest nearest frame. We can also experiment with taking the nearest frame.

**Comment by ndujar** [comment]
Sampling and array creation algorithm has been re-implemented.
It now creates two full lists of presentation timestamps (pts) one for source, one for rendition by multiplying frames numbers by the given delta_time (1/24, 1/30, ...). Depending on whether we are upsampling or downsampling), we randomly pick a number of pts (max_samples) from the longest list.
To create the list with the nearest pts from the rendition we get the minimum differences between the picked frames and the rendition list and iterate frame by frame.
When the difference between the current pts and the corresponding sample is almost zero:
` add_condition = abs(pts - nearest_frames[sample_num]) < 0.000001`
we include that frame in the list of numpy arrays to be passed to the verifier.

Unfortunately, this hasn't solved our issue:

TPR:
- Number of verifications (720p + 360p + 240p): 402
- Number of false negatives: 130
- TPR: 0.6766
